import Foundation

/// Where the generated code finds the shipped strings.
enum BundleSource: String {
    /// An app target: `Bundle.main`.
    case main
    /// A Swift package target with resources: `Bundle.module`.
    case module
    /// An Xcode target, app or framework: the bundle holding the generated code.
    case token
}

enum AccessLevel: String, Decodable {
    case `internal`, `public`, `package`
}

/// `localizeme-strings.json`, all of it optional:
/// `{"typeName": "L10n", "accessLevel": "internal", "sourceLanguage": "en"}`.
struct Configuration: Decodable, Equatable {
    static let fileName = "localizeme-strings.json"

    var typeName = "L10n"
    var accessLevel = AccessLevel.internal
    /// The language whose `.lproj` supplies the values, for `.strings` and
    /// `.stringsdict` tables. A string catalog names its own.
    var sourceLanguage: String?

    init() {}

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        typeName = try container.decodeIfPresent(String.self, forKey: .typeName) ?? typeName
        accessLevel = try container.decodeIfPresent(AccessLevel.self, forKey: .accessLevel) ?? accessLevel
        sourceLanguage = try container.decodeIfPresent(String.self, forKey: .sourceLanguage)
    }

    private enum CodingKeys: String, CodingKey {
        case typeName, accessLevel, sourceLanguage
    }

    static func load(_ url: URL) throws -> Configuration {
        let configuration: Configuration
        do {
            configuration = try JSONDecoder().decode(Configuration.self, from: Data(contentsOf: url))
        } catch {
            throw CatalogError("\(url.path): \(error.localizedDescription) Expected {\"typeName\": \"L10n\", \"accessLevel\": \"internal\" | \"public\" | \"package\", \"sourceLanguage\": \"en\"}.")
        }
        guard Naming.isPlainIdentifier(configuration.typeName) else {
            throw CatalogError("\(url.path): typeName \"\(configuration.typeName)\" is not a Swift type name.")
        }
        return configuration
    }
}

enum Generator {
    /// Renders the Swift file for `tables`, plus the warnings about keys that
    /// did not get the accessor they seem to want.
    static func render(
        _ tables: [StringTable], sources: [String], configuration: Configuration, bundle: BundleSource
    ) -> (source: String, warnings: [Warning]) {
        var warnings: [Warning] = []
        let access = configuration.accessLevel.rawValue
        // Xcode 26 projects make declarations main-actor isolated by default;
        // strings are wanted from any thread. The same compiler builds this
        // tool and the file it writes, so this matches what compiles it.
        #if compiler(>=6.2)
        let isolation = "nonisolated "
        #else
        let isolation = ""
        #endif

        var lines: [String] = []
        let names = Set(sources).sorted()
        lines.append("// Generated by the LocalizeMeStrings plugin from \(names.isEmpty ? "no string tables" : names.joined(separator: ", ")).")
        lines.append("// Do not edit: every build rewrites this file.")
        lines.append("// swiftlint:disable all")
        lines.append("")
        lines.append("import Foundation")
        lines.append("import LocalizeMe")
        lines.append("")
        lines.append("\(access) enum \(configuration.typeName) {")

        let main = tables.first { $0.name == "Localizable" }
        let others = tables.filter { $0.name != "Localizable" }
        var body: [String] = []
        if let main {
            body += members(of: main, lookupTable: nil, indent: "    ", access: access, isolation: isolation, warnings: &warnings)
        }
        var typeNames: Set<String> = []
        for table in others {
            var name = Naming.typeName(for: table.name)
            var suffix = 2
            while typeNames.contains(name) {
                name = Naming.safeIdentifier(Naming.bare(Naming.typeName(for: table.name)) + String(suffix))
                suffix += 1
            }
            typeNames.insert(name)
            if !body.isEmpty { body.append("") }
            body.append("    \(access) enum \(name) {")
            body += members(of: table, lookupTable: table.name, indent: "        ", access: access, isolation: isolation, warnings: &warnings)
            body.append("    }")
        }
        lines += body
        lines.append("}")
        lines.append("")
        lines.append("private enum _LocalizeMeStrings {")
        lines.append("    \(isolation)static func string(_ key: String, _ table: String?) -> String {")
        lines.append("        LocalizeMe.string(key) ?? bundle.localizedString(forKey: key, value: nil, table: table)")
        lines.append("    }")
        lines.append("")
        lines.append("    \(isolation)static func string(_ key: String, _ table: String?, _ arguments: CVarArg...) -> String {")
        lines.append("        let shipped = bundle.localizedString(forKey: key, value: nil, table: table)")
        lines.append("        return String(format: LocalizeMe.string(key, fallback: shipped), locale: Locale.current, arguments: arguments)")
        lines.append("    }")
        lines.append("")
        switch bundle {
        case .main:
            lines.append("    \(isolation)static var bundle: Bundle { Bundle.main }")
        case .module:
            lines.append("    \(isolation)static var bundle: Bundle { Bundle.module }")
        case .token:
            lines.append("    \(isolation)static var bundle: Bundle { Bundle(for: _LocalizeMeStringsBundleToken.self) }")
        }
        lines.append("}")
        if bundle == .token {
            lines.append("")
            lines.append("private final class _LocalizeMeStringsBundleToken {}")
        }
        lines.append("")
        return (lines.joined(separator: "\n"), warnings)
    }

    /// One accessor per key, in key order: a property for plain text, a
    /// function taking the arguments for a format string.
    private static func members(
        of table: StringTable, lookupTable: String?, indent: String, access: String, isolation: String,
        warnings: inout [Warning]
    ) -> [String] {
        var lines: [String] = []
        var used: Set<String> = []
        let tableLiteral = lookupTable.map(literal) ?? "nil"
        for entry in table.entries.values.sorted(by: { $0.key < $1.key }) {
            var member = Naming.memberName(for: entry.key)
            if used.contains(member) {
                var suffix = 2
                while used.contains(Naming.safeIdentifier(Naming.bare(member) + String(suffix))) { suffix += 1 }
                let renamed = Naming.safeIdentifier(Naming.bare(member) + String(suffix))
                warnings.append(Warning(file: table.file, message: "\"\(entry.key)\" is named \(renamed): another key in \(table.name) already took \(member)"))
                member = renamed
            }
            used.insert(member)

            if !lines.isEmpty { lines.append("") }
            lines += documentation(for: entry, indent: indent)
            let call = "_LocalizeMeStrings.string(\(literal(entry.key)), \(tableLiteral)"
            switch accessor(for: entry, in: table, warnings: &warnings) {
            case nil:
                lines.append("\(indent)\(access) \(isolation)static var \(member): String { \(call)) }")
            case let types?:
                let parameters = types.enumerated().map { "_ p\($0.offset + 1): \($0.element)" }.joined(separator: ", ")
                let arguments = types.indices.map { ", p\($0 + 1)" }.joined()
                lines.append("\(indent)\(access) \(isolation)static func \(member)(\(parameters)) -> String {")
                lines.append("\(indent)    \(call)\(arguments))")
                lines.append("\(indent)}")
            }
        }
        return lines
    }

    /// The parameter types for a format string, or nil for text shown as
    /// written. A string that reads as formatted but cannot be formatted
    /// safely is shown as written too, with a warning.
    static func accessor(for entry: StringEntry, in table: StringTable, warnings: inout [Warning]) -> [String]? {
        let positions = entry.variables.compactMapValues(\.position)
        let specifiers = entry.variables.mapValues(\.specifier)
        func refuse(_ reason: String) -> [String]? {
            warnings.append(Warning(file: table.file, message: "\"\(entry.key)\" \(reason), so its accessor is a property that shows it as written"))
            return nil
        }
        guard let strict = Placeholders.scan(entry.format, strict: true, variablePositions: positions) else {
            return refuse("has a placeholder that cannot be formatted safely (%n, or one argument used as two types)")
        }
        guard !strict.isEmpty else { return nil }
        guard let slots = Placeholders.scan(entry.format, strict: false, variablePositions: positions) else {
            return refuse("has a placeholder that cannot be formatted safely")
        }
        let count = slots.keys.max() ?? 0
        guard slots.count == count else {
            return refuse("skips an argument position")
        }
        return (1...count).map { Placeholders.swiftType(for: slots[$0]!, specifiers: specifiers) }
    }

    /// The source-language value, and the table's comment when it has one.
    private static func documentation(for entry: StringEntry, indent: String) -> [String] {
        var lines = docLines(entry.preview).map { "\(indent)/// \($0)" }
        if let comment = entry.comment, !comment.isEmpty {
            if !lines.isEmpty { lines.append("\(indent)///") }
            lines += docLines(comment).map { "\(indent)/// \($0)" }
        }
        return lines
    }

    private static func docLines(_ text: String) -> [String] {
        text.components(separatedBy: CharacterSet(charactersIn: "\r\n\u{2028}\u{2029}"))
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    /// `text` as a Swift string literal.
    static func literal(_ text: String) -> String {
        var out = "\""
        for scalar in text.unicodeScalars {
            switch scalar {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            case "\0": out += "\\0"
            default:
                let value = scalar.value
                if value < 0x20 || (0x7F...0x9F).contains(value) || value == 0x2028 || value == 0x2029 {
                    out += "\\u{\(String(value, radix: 16))}"
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        return out + "\""
    }

    /// Writes `source` unless the file already says exactly that, so an
    /// unchanged table does not recompile the target.
    static func write(_ source: String, to url: URL) throws {
        let data = Data(source.utf8)
        if let existing = try? Data(contentsOf: url), existing == data { return }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: .atomic)
    }
}

/// `LocalizeMeStringsGenerator --output <file.swift> --bundle main|module|token
/// [--config <localizeme-strings.json>] <table files>…`, as the plugin runs it.
public enum GeneratorCommand {
    /// Runs the command, printing warnings and errors the way a build shows
    /// them; the exit status.
    public static func main(_ arguments: [String]) -> Int32 {
        do {
            for warning in try run(arguments) {
                FileHandle.standardError.write(Data((warning.description + "\n").utf8))
            }
            return 0
        } catch {
            FileHandle.standardError.write(Data("error: \(error.localizedDescription)\n".utf8))
            return 1
        }
    }

    static func run(_ arguments: [String]) throws -> [Warning] {
        var output: URL?
        var bundle = BundleSource.main
        var configuration = Configuration()
        var inputs: [URL] = []
        var rest = arguments[...]
        while let argument = rest.popFirst() {
            switch argument {
            case "--output":
                output = rest.popFirst().map { URL(fileURLWithPath: $0) }
            case "--bundle":
                guard let value = rest.popFirst(), let source = BundleSource(rawValue: value) else {
                    throw CatalogError("--bundle takes main, module or token")
                }
                bundle = source
            case "--config":
                guard let path = rest.popFirst() else { throw CatalogError("--config takes a path") }
                configuration = try Configuration.load(URL(fileURLWithPath: path))
            default:
                inputs.append(URL(fileURLWithPath: argument))
            }
        }
        guard let output else { throw CatalogError("--output is required") }
        let tables = inputs.filter(Catalog.isTable)
        let (read, readWarnings) = Catalog.read(tables, sourceLanguage: configuration.sourceLanguage)
        let (source, warnings) = Generator.render(
            read, sources: tables.map(\.lastPathComponent), configuration: configuration, bundle: bundle
        )
        try Generator.write(source, to: output)
        return readWarnings + warnings
    }
}
