import Foundation
import Testing
@testable import LocalizeMeStringsCore

struct GeneratorTests {
    #if compiler(>=6.2)
    let isolation = "nonisolated "
    #else
    let isolation = ""
    #endif

    func table(_ name: String, _ entries: [StringEntry], file: String? = nil) -> StringTable {
        StringTable(name: name, entries: Dictionary(uniqueKeysWithValues: entries.map { ($0.key, $0) }), file: file)
    }

    @Test func rendersPropertiesFunctionsAndTables() {
        let (source, warnings) = Generator.render(
            [
                table("Localizable", [
                    StringEntry(key: "home.title", format: "Home"),
                    StringEntry(key: "greeting", format: "Hello %@"),
                ]),
                table("Onboarding", [StringEntry(key: "welcome", format: "Welcome!", comment: "First screen")]),
            ],
            sources: ["Localizable.xcstrings", "Onboarding.xcstrings"],
            configuration: Configuration(),
            bundle: .token
        )
        #expect(warnings.isEmpty)
        let expected = """
        // Generated by the LocalizeMeStrings plugin from Localizable.xcstrings, Onboarding.xcstrings.
        // Do not edit: every build rewrites this file.
        // swiftlint:disable all

        import Foundation
        import LocalizeMe

        internal enum L10n {
            /// Hello %@
            internal \(isolation)static func greeting(_ p1: String) -> String {
                _LocalizeMeStrings.string("greeting", nil, p1)
            }

            /// Home
            internal \(isolation)static var homeTitle: String { _LocalizeMeStrings.string("home.title", nil) }

            internal enum Onboarding {
                /// Welcome!
                ///
                /// First screen
                internal \(isolation)static var welcome: String { _LocalizeMeStrings.string("welcome", "Onboarding") }
            }
        }

        private enum _LocalizeMeStrings {
            \(isolation)static func string(_ key: String, _ table: String?) -> String {
                LocalizeMe.string(key) ?? bundle.localizedString(forKey: key, value: nil, table: table)
            }

            \(isolation)static func string(_ key: String, _ table: String?, _ arguments: CVarArg...) -> String {
                let shipped = bundle.localizedString(forKey: key, value: nil, table: table)
                return String(format: LocalizeMe.string(key, fallback: shipped), locale: Locale.current, arguments: arguments)
            }

            \(isolation)static var bundle: Bundle { Bundle(for: _LocalizeMeStringsBundleToken.self) }
        }

        private final class _LocalizeMeStringsBundleToken {}

        """
        #expect(source == expected)
    }

    @Test func theConfigurationNamesTheTypeAndItsAccess() {
        var configuration = Configuration()
        configuration.typeName = "Strings"
        configuration.accessLevel = .public
        let (source, _) = Generator.render(
            [table("Localizable", [StringEntry(key: "ok", format: "OK")])],
            sources: [], configuration: configuration, bundle: .module
        )
        #expect(source.contains("public enum Strings {"))
        #expect(source.contains("public \(isolation)static var ok: String"))
        #expect(source.contains("static var bundle: Bundle { Bundle.module }"))
        #expect(!source.contains("_LocalizeMeStringsBundleToken"))
    }

    @Test func collidingNamesAreNumberedAndReported() {
        let (source, warnings) = Generator.render(
            [table("Localizable", [
                StringEntry(key: "home.title", format: "A"),
                StringEntry(key: "home_title", format: "B"),
                StringEntry(key: "default", format: "C"),
                StringEntry(key: "Default", format: "D"),
            ], file: "/app/Localizable.xcstrings")],
            sources: [], configuration: Configuration(), bundle: .main
        )
        #expect(source.contains("static var homeTitle: String { _LocalizeMeStrings.string(\"home.title\""))
        #expect(source.contains("static var homeTitle2: String { _LocalizeMeStrings.string(\"home_title\""))
        #expect(source.contains("static var `default`: String { _LocalizeMeStrings.string(\"Default\""))
        #expect(source.contains("static var default2: String { _LocalizeMeStrings.string(\"default\""))
        #expect(warnings.count == 2)
        #expect(warnings.allSatisfy { $0.file == "/app/Localizable.xcstrings" })
    }

    @Test func stringsThatCannotBeFormattedSafelyBecomePropertiesWithAWarning() {
        var warnings: [Warning] = []
        let table = table("Localizable", [], file: "/app/Localizable.strings")
        #expect(Generator.accessor(for: StringEntry(key: "a", format: "%1$@ and %3$@"), in: table, warnings: &warnings) == nil)
        #expect(Generator.accessor(for: StringEntry(key: "b", format: "Wrote %n"), in: table, warnings: &warnings) == nil)
        #expect(warnings.count == 2)
        #expect(warnings[0].description == #"/app/Localizable.strings: warning: "a" skips an argument position, so its accessor is a property that shows it as written"#)
        // Plain text with a percent sign is no reason to warn.
        #expect(Generator.accessor(for: StringEntry(key: "c", format: "20% off"), in: table, warnings: &warnings) == nil)
        #expect(warnings.count == 2)
    }

    @Test func formatStringsGetTypedParameters() {
        var warnings: [Warning] = []
        let table = table("Localizable", [])
        func types(_ entry: StringEntry) -> [String]? { Generator.accessor(for: entry, in: table, warnings: &warnings) }
        #expect(types(StringEntry(key: "a", format: "%2$@ sent %1$lld")) == ["Int", "String"])
        #expect(types(StringEntry(key: "b", format: "%.1f%% done")) == ["Double"])
        var plural = StringEntry(key: "c", format: "%#@items@")
        plural.variables = ["items": .init(specifier: "lld")]
        #expect(types(plural) == ["Int"])
        // A format string with a stray % takes what String(format:) will read.
        #expect(types(StringEntry(key: "d", format: "%lld at 20% off")) == ["Int", "Int"])
        #expect(warnings.isEmpty)
    }

    @Test func literalsEscapeWhatSwiftSourceCannotHold() {
        #expect(Generator.literal("plain") == #""plain""#)
        #expect(Generator.literal("a\"b\\c\n\t\u{7}\u{2028}") == #""a\"b\\c\n\t\u{7}\u{2028}""#)
        #expect(Generator.literal("\\(not interpolated)") == #""\\(not interpolated)""#)
    }

    @Test func theCommandWritesOnlyWhenTheOutputChanges() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: root) }
        let strings = root.appendingPathComponent("en.lproj/Localizable.strings")
        try FileManager.default.createDirectory(at: strings.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data(#""home.title" = "Home";"#.utf8).write(to: strings)
        let output = root.appendingPathComponent("out/LocalizeMeStrings.swift")
        let arguments = ["--output", output.path, "--bundle", "main", strings.path]

        #expect(try GeneratorCommand.run(arguments).isEmpty)
        let first = try String(contentsOf: output, encoding: .utf8)
        #expect(first.contains("static var homeTitle: String"))
        let written = try FileManager.default.attributesOfItem(atPath: output.path)[.modificationDate] as? Date
        Thread.sleep(forTimeInterval: 1.1)
        _ = try GeneratorCommand.run(arguments)
        let rewritten = try FileManager.default.attributesOfItem(atPath: output.path)[.modificationDate] as? Date
        #expect(written == rewritten)
    }

    @Test func theCommandReadsItsConfigurationAndRefusesABadOne() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        let config = root.appendingPathComponent("localizeme-strings.json")
        let output = root.appendingPathComponent("LocalizeMeStrings.swift")

        try Data(#"{"typeName": "Strings", "accessLevel": "package"}"#.utf8).write(to: config)
        _ = try GeneratorCommand.run(["--output", output.path, "--config", config.path])
        #expect(try String(contentsOf: output, encoding: .utf8).contains("package enum Strings {"))

        try Data(#"{"typeName": "my strings"}"#.utf8).write(to: config)
        #expect(throws: CatalogError.self) { try GeneratorCommand.run(["--output", output.path, "--config", config.path]) }
        try Data(#"{"accessLevel": "open"}"#.utf8).write(to: config)
        #expect(throws: CatalogError.self) { try GeneratorCommand.run(["--output", output.path, "--config", config.path]) }
    }
}
